// PROXY — real implementation moved to @lucid-l2/engine
export {
  setAnchoringConfig,
  getAnchoringConfig,
  setAuthorityKeypair,
  loadAuthorityFromSecretKey,
  getConnection,
  deriveEpochRecordPDA,
  deriveEpochRecordV2PDA,
  deriveEpochBatchRecordPDA,
  buildCommitEpochInstruction,
  buildInitEpochInstruction,
  buildCommitEpochsInstruction,
  buildInitEpochsInstruction,
  buildCommitEpochV2Instruction,
  buildInitEpochV2Instruction,
  commitEpochRoot,
  commitEpochRootsBatch,
  verifyEpochAnchor,
  getAnchorTransaction,
  checkAnchoringHealth,
  resetAnchoringState,
  enableMockMode,
  disableMockMode,
} from '../../../packages/engine/src/receipt/anchoringService';
export type { AnchoringConfig, AnchorResult, VerifyAnchorResult } from '../../../packages/engine/src/receipt/anchoringService';
