// PROXY — real implementation moved to @lucid-l2/engine
export {
  createEpoch,
  getCurrentEpoch,
  getEpoch,
  addReceiptToEpoch,
  prepareEpochForFinalization,
  finalizeEpoch,
  failEpoch,
  retryEpoch,
  listEpochs,
  getEpochForReceipt,
  getAllEpochs,
  getEpochStats,
  getEpochsReadyForFinalization,
  getFailedEpochs,
  setEpochConfig,
  getEpochConfig,
  startAutoFinalization,
  stopAutoFinalization,
  isAutoFinalizationRunning,
  setAnchorCallback,
  resetEpochStore,
  shouldFinalizeEpoch,
} from '../../../packages/engine/src/receipt/epochService';
export type { EpochStatus, Epoch, EpochSummary, EpochFilters, PaginatedEpochs, EpochConfig } from '../../../packages/engine/src/receipt/epochService';
