// PROXY — real implementation moved to @lucid-l2/engine
export {
  createReceipt,
  createExtendedReceipt,
  createReceiptFromJobResult,
  verifyReceiptHash,
  verifyReceipt,
  verifyExtendedReceipt,
  getReceiptProof,
  verifyReceiptProof,
  computeQuoteHash,
  computeJobHash,
  computeInputHash,
  computeOutputsHash,
  verifyQuoteHash,
  verifyJobHash,
  validateExtendedReceiptInput,
  assertValidExtendedReceiptInput,
  getReceipt,
  getExtendedReceipt,
  listReceipts,
  listExtendedReceipts,
  getMmrRoot,
  getMmrLeafCount,
  getSignerPublicKey,
  resetReceiptStore,
} from '../../../packages/engine/src/receipt/receiptService';
export type { ReceiptBody, RunReceiptInput, SignedReceipt, ReceiptVerifyResult, ExtendedReceiptBody, ExtendedSignedReceipt, ReceiptValidationError, ReceiptValidationResult } from '../../../packages/engine/src/receipt/receiptService';
