[toolchain]
anchor_version = "0.31.1"

[provider]
cluster = "localnet"
wallet  = "~/.config/solana/id.json"

[programs.localnet]
# thought_epoch = "J1JNYJB41UeyyR3qYFjwxZ2RsD71JRm3ULYZG6bLhm3c"
# gas_utils = "11111111111111111111111111111111"

[workspace]
members = [
    "programs/thought-epoch"
]
