[toolchain]
anchor_version = "0.31.1"

[provider]
cluster = "devnet"
wallet  = "/home/debian/.config/solana/id.json"

[programs.localnet]
thought_epoch = "9YhfaLoUZYLzu3xRQevRom4qj8oTf5TGpuoWptvStKDu"
gas_utils = "EzuUhxtNAz1eRfAPypm6eAepe8fRQBrBPSo4Qcp1w3hm"
lucid_passports = "FhoemNdqwPMt8nmX4HT3WpSqUuqeAUXRb7WchAehmSaL"
lucid_agent_wallet = "AJGpTWXbhvdYMxSah6GAKzykvfkYo2ViQpWGMbimQsph"
lucid_zkml_verifier = "69cJRFGWijD1FdapQ2vz7VP6x2jcXRQyBws9VzzPpqAN"

[programs.devnet]
thought_epoch = "9YhfaLoUZYLzu3xRQevRom4qj8oTf5TGpuoWptvStKDu"
gas_utils = "EzuUhxtNAz1eRfAPypm6eAepe8fRQBrBPSo4Qcp1w3hm"
lucid_passports = "FhoemNdqwPMt8nmX4HT3WpSqUuqeAUXRb7WchAehmSaL"
lucid_agent_wallet = "AJGpTWXbhvdYMxSah6GAKzykvfkYo2ViQpWGMbimQsph"
lucid_zkml_verifier = "69cJRFGWijD1FdapQ2vz7VP6x2jcXRQyBws9VzzPpqAN"

[programs.mainnet]
thought_epoch = "11111111111111111111111111111111"
gas_utils = "EzuUhxtNAz1eRfAPypm6eAepe8fRQBrBPSo4Qcp1w3hm"
lucid_passports = "11111111111111111111111111111111"
lucid_agent_wallet = "AJGpTWXbhvdYMxSah6GAKzykvfkYo2ViQpWGMbimQsph"
lucid_zkml_verifier = "69cJRFGWijD1FdapQ2vz7VP6x2jcXRQyBws9VzzPpqAN"

[workspace]
members = [
    "programs/thought-epoch",
    "programs/lucid-passports",
    "programs/gas-utils",
    "programs/lucid-agent-wallet",
    "programs/lucid-zkml-verifier"
]
