/** @deprecated Use `lucid launch --image` or `--runtime base` instead. This adapter will move to examples/ in a future release. */
// offchain/packages/engine/src/runtime/CrewAIAdapter.ts
// CrewAI adapter — generates YAML-first agent and task definitions

import { IRuntimeAdapter, RuntimeArtifact } from './IRuntimeAdapter';

/**
 * CrewAI Adapter
 *
 * Generates YAML-first CrewAI agent and task definitions.
 * Best for role-based multi-agent teams.
 */
export class CrewAIAdapter implements IRuntimeAdapter {
  readonly name = 'crewai';
  readonly version = '1.0.0';
  readonly language = 'python' as const;

  canHandle(descriptor: any): boolean {
    return true;
  }

  async generate(descriptor: any, passportId: string): Promise<RuntimeArtifact> {
    const config = descriptor.agent_config;
    const files = new Map<string, string>();
    const maxIter = config.stop_conditions?.find((s: any) => s.type === 'max_steps')?.value || 50;

    // agents.yaml
    files.set('config/agents.yaml', `${passportId}:
  role: AI Agent
  goal: ${config.system_prompt.substring(0, 200).replace(/\n/g, ' ')}
  backstory: >
    ${config.system_prompt.replace(/\n/g, '\n    ')}
  llm: ${config.model_passport_id}
  max_iter: ${maxIter}
  tools:
    - call_mcp_tool
`);

    // tasks.yaml
    files.set('config/tasks.yaml', `main_task:
  description: >
    Execute the given goal using available tools and knowledge.
    Goal: {goal}
  expected_output: >
    A comprehensive result addressing the goal with supporting evidence.
  agent: ${passportId}
  output_file: result.md
`);

    // crew.py
    files.set('crew.py', `"""
Lucid Agent Crew: ${passportId}
Generated by Lucid-L2 CrewAI Adapter
"""
import os
import json
import httpx
from crewai import Agent, Task, Crew, Process
from crewai.tools import BaseTool

MCPGATE_URL = os.environ.get("MCPGATE_URL", "https://mcpgate-api-production.up.railway.app")
MCPGATE_API_KEY = os.environ.get("MCPGATE_API_KEY", "")


class MCPTool(BaseTool):
    name: str = "call_mcp_tool"
    description: str = "Call an MCP tool through Lucid MCPGate"

    def _run(self, server: str, tool_name: str, arguments: str) -> str:
        resp = httpx.post(
            f"{MCPGATE_URL}/v1/tools/call",
            headers={
                "Authorization": f"Bearer {MCPGATE_API_KEY}",
                "Content-Type": "application/json",
            },
            json={"server": server, "tool": tool_name, "arguments": json.loads(arguments)},
            timeout=30.0,
        )
        resp.raise_for_status()
        return json.dumps(resp.json())


def create_crew(goal: str) -> Crew:
    agent = Agent(
        role="AI Agent",
        goal=goal,
        backstory=${JSON.stringify(config.system_prompt)},
        tools=[MCPTool()],
        llm="${config.model_passport_id}",
        max_iter=${maxIter},
        verbose=True,
    )

    task = Task(
        description=f"Execute: {goal}",
        expected_output="Comprehensive result",
        agent=agent,
    )

    return Crew(
        agents=[agent],
        tasks=[task],
        process=Process.sequential,
        verbose=True,
    )


# --- HTTP Server ---
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(title=f"Lucid Agent: ${passportId}")


class RunRequest(BaseModel):
    prompt: str


@app.get("/health")
async def health():
    return {"status": "healthy", "agent": "${passportId}", "adapter": "crewai"}


@app.post("/run")
async def run_agent(req: RunRequest):
    try:
        crew = create_crew(req.prompt)
        result = crew.kickoff()
        return {"ok": True, "text": str(result)}
    except Exception as e:
        return {"ok": False, "error": str(e)}


if __name__ == "__main__":
    import uvicorn
    port = int(os.environ.get("PORT", "3100"))
    uvicorn.run(app, host="0.0.0.0", port=port)
`);

    files.set('requirements.txt', `crewai>=0.80.0
httpx>=0.27.0
fastapi>=0.109.0
uvicorn>=0.27.0
`);

    const dockerfile = `FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 3100
CMD ["python", "crew.py"]
`;
    files.set('Dockerfile', dockerfile);

    return {
      adapter: this.name,
      files,
      entrypoint: 'crew.py',
      dependencies: { 'crewai': '>=0.80.0', 'httpx': '>=0.27.0', 'fastapi': '>=0.109.0' },
      env_vars: { MCPGATE_URL: '', MCPGATE_API_KEY: '', PORT: '3100' },
      dockerfile,
    };
  }
}
