/** @deprecated Use `lucid launch --image` or `--runtime base` instead. This adapter will move to examples/ in a future release. */
// offchain/packages/engine/src/runtime/OpenAIAgentsAdapter.ts
// OpenAI Agents SDK adapter — generates Python agent with handoffs + guardrails

import { IRuntimeAdapter, RuntimeArtifact } from './IRuntimeAdapter';

/**
 * OpenAI Agents SDK Adapter
 *
 * Generates Python code using the OpenAI Agents SDK (openai-agents).
 * Supports handoffs, guardrails, and tracing.
 */
export class OpenAIAgentsAdapter implements IRuntimeAdapter {
  readonly name = 'openai-agents';
  readonly version = '1.0.0';
  readonly language = 'python' as const;

  canHandle(descriptor: any): boolean {
    return true; // OpenAI Agents SDK supports all workflow types
  }

  async generate(descriptor: any, passportId: string): Promise<RuntimeArtifact> {
    const config = descriptor.agent_config;
    const files = new Map<string, string>();

    const mcpServerTools = (config.mcp_servers || []).map((server: string) => {
      const safeName = server.replace(/[^a-zA-Z0-9]/g, '_');
      return `@function_tool
async def ${safeName}_tool(tool_name: str, arguments: str) -> str:
    """Call a tool on the ${server} MCP server.

    Args:
        tool_name: Name of the tool to execute
        arguments: JSON string of tool arguments
    """
    return await call_mcp_tool("${server}", tool_name, arguments)
`;
    }).join('\n');

    const mcpServerToolNames = (config.mcp_servers || []).map((s: string) =>
      `        ${s.replace(/[^a-zA-Z0-9]/g, '_')}_tool,`
    ).join('\n');

    files.set('agent.py', `"""
Lucid Agent: ${passportId}
Generated by Lucid-L2 OpenAI Agents Adapter
"""
import os
import json
import httpx
from agents import Agent, Runner, function_tool, GuardrailFunctionOutput, InputGuardrail
from agents.tracing import set_tracing_disabled

# --- Configuration ---
TRUSTGATE_URL = os.environ.get("TRUSTGATE_URL", "https://trustgate-api-production.up.railway.app")
TRUSTGATE_API_KEY = os.environ.get("TRUSTGATE_API_KEY", "")
MCPGATE_URL = os.environ.get("MCPGATE_URL", "https://mcpgate-api-production.up.railway.app")
MCPGATE_API_KEY = os.environ.get("MCPGATE_API_KEY", "")


# --- MCP Tool Bridge ---
@function_tool
async def call_mcp_tool(server: str, tool_name: str, arguments: str) -> str:
    """Call an MCP tool through Lucid MCPGate.

    Args:
        server: MCP server name (e.g., 'builtin:github')
        tool_name: Tool name on the server
        arguments: JSON string of tool arguments
    """
    async with httpx.AsyncClient() as client:
        resp = await client.post(
            f"{MCPGATE_URL}/v1/tools/call",
            headers={
                "Authorization": f"Bearer {MCPGATE_API_KEY}",
                "Content-Type": "application/json",
            },
            json={
                "server": server,
                "tool": tool_name,
                "arguments": json.loads(arguments),
            },
            timeout=30.0,
        )
        resp.raise_for_status()
        return json.dumps(resp.json())


${mcpServerTools}


# --- Agent Definition ---
agent = Agent(
    name="${passportId}",
    instructions=${JSON.stringify(config.system_prompt)},
    model="${config.model_passport_id}",
    tools=[
        call_mcp_tool,
${mcpServerToolNames}
    ],
)

${config.workflow_type !== 'single' && config.sub_agents?.length ? `
# --- Multi-Agent Setup ---
# Sub-agents would be loaded from their passports here
# Handoff rules: ${JSON.stringify(config.handoff_rules || [])}
` : ''}

# --- HTTP Server ---
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(title=f"Lucid Agent: ${passportId}")


class RunRequest(BaseModel):
    prompt: str
    stream: bool = False


class RunResponse(BaseModel):
    ok: bool
    text: str = ""
    error: str = ""


@app.get("/health")
async def health():
    return {"status": "healthy", "agent": "${passportId}", "adapter": "openai-agents"}


@app.post("/run")
async def run_agent(req: RunRequest) -> RunResponse:
    try:
        result = await Runner.run(agent, req.prompt)
        return RunResponse(ok=True, text=result.final_output or "")
    except Exception as e:
        return RunResponse(ok=False, error=str(e))

${descriptor.agent_config.a2a_enabled ? `

# --- A2A Protocol ---
@app.get("/.well-known/agent.json")
async def agent_card():
    return {
        "name": "${passportId}",
        "description": ${JSON.stringify(config.system_prompt.substring(0, 200))},
        "url": os.environ.get("AGENT_URL", "http://localhost:3100"),
        "version": "1.0.0",
        "capabilities": ${JSON.stringify(config.a2a_capabilities || [])},
        "authentication": {"type": "bearer"},
        "defaultInputModes": ["text"],
        "defaultOutputModes": ["text"],
    }


@app.post("/tasks/send")
async def a2a_task(body: dict):
    message = body.get("message", {})
    parts = message.get("parts", [])
    text = parts[0].get("text", "") if parts else ""
    try:
        result = await Runner.run(agent, text)
        return {
            "id": f"task_{id(body)}",
            "status": {"state": "completed"},
            "artifacts": [{"parts": [{"type": "text", "text": result.final_output or ""}]}],
        }
    except Exception as e:
        return {
            "id": f"task_{id(body)}",
            "status": {"state": "failed", "message": str(e)},
        }
` : ''}

if __name__ == "__main__":
    import uvicorn
    port = int(os.environ.get("PORT", "3100"))
    uvicorn.run(app, host="0.0.0.0", port=port)
`);

    files.set('requirements.txt', `openai-agents>=0.1.0
httpx>=0.27.0
fastapi>=0.109.0
uvicorn>=0.27.0
pydantic>=2.0.0
`);

    const dockerfile = `FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 3100
HEALTHCHECK --interval=30s --timeout=5s CMD curl -f http://localhost:3100/health || exit 1
CMD ["python", "agent.py"]
`;
    files.set('Dockerfile', dockerfile);

    return {
      adapter: this.name,
      files,
      entrypoint: 'agent.py',
      dependencies: {
        'openai-agents': '>=0.1.0',
        'httpx': '>=0.27.0',
        'fastapi': '>=0.109.0',
        'uvicorn': '>=0.27.0',
      },
      env_vars: {
        TRUSTGATE_URL: '',
        TRUSTGATE_API_KEY: '',
        MCPGATE_URL: '',
        MCPGATE_API_KEY: '',
        OPENAI_API_KEY: '',
        PORT: '3100',
      },
      dockerfile,
    };
  }
}
