"""
Lucid Agent Crew: passport_new_agent_123
Generated by Lucid-L2 CrewAI Adapter
"""
import os
import json
import httpx
from crewai import Agent, Task, Crew, Process
from crewai.tools import BaseTool

MCPGATE_URL = os.environ.get("MCPGATE_URL", "https://mcpgate-api-production.up.railway.app")
MCPGATE_API_KEY = os.environ.get("MCPGATE_API_KEY", "")


class MCPTool(BaseTool):
    name: str = "call_mcp_tool"
    description: str = "Call an MCP tool through Lucid MCPGate"

    def _run(self, server: str, tool_name: str, arguments: str) -> str:
        resp = httpx.post(
            f"{MCPGATE_URL}/v1/tools/call",
            headers={
                "Authorization": f"Bearer {MCPGATE_API_KEY}",
                "Content-Type": "application/json",
            },
            json={"server": server, "tool": tool_name, "arguments": json.loads(arguments)},
            timeout=30.0,
        )
        resp.raise_for_status()
        return json.dumps(resp.json())


def create_crew(goal: str) -> Crew:
    agent = Agent(
        role="AI Agent",
        goal=goal,
        backstory="You are a helpful agent.",
        tools=[MCPTool()],
        llm="passport_model_abc",
        max_iter=50,
        verbose=True,
    )

    task = Task(
        description=f"Execute: {goal}",
        expected_output="Comprehensive result",
        agent=agent,
    )

    return Crew(
        agents=[agent],
        tasks=[task],
        process=Process.sequential,
        verbose=True,
    )


# --- HTTP Server ---
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(title=f"Lucid Agent: passport_new_agent_123")


class RunRequest(BaseModel):
    prompt: str


@app.get("/health")
async def health():
    return {"status": "healthy", "agent": "passport_new_agent_123", "adapter": "crewai"}


@app.post("/run")
async def run_agent(req: RunRequest):
    try:
        crew = create_crew(req.prompt)
        result = crew.kickoff()
        return {"ok": True, "text": str(result)}
    except Exception as e:
        return {"ok": False, "error": str(e)}


if __name__ == "__main__":
    import uvicorn
    port = int(os.environ.get("PORT", "3100"))
    uvicorn.run(app, host="0.0.0.0", port=port)
