/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteAssetPricingRequest = {
  passportId: string;
};

/**
 * Deleted
 */
export type DeleteAssetPricingResponse = {
  success: boolean;
  deleted: boolean;
};

/** @internal */
export type DeleteAssetPricingRequest$Outbound = {
  passport_id: string;
};

/** @internal */
export const DeleteAssetPricingRequest$outboundSchema: z.ZodMiniType<
  DeleteAssetPricingRequest$Outbound,
  DeleteAssetPricingRequest
> = z.pipe(
  z.object({
    passportId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      passportId: "passport_id",
    });
  }),
);

export function deleteAssetPricingRequestToJSON(
  deleteAssetPricingRequest: DeleteAssetPricingRequest,
): string {
  return JSON.stringify(
    DeleteAssetPricingRequest$outboundSchema.parse(deleteAssetPricingRequest),
  );
}

/** @internal */
export const DeleteAssetPricingResponse$inboundSchema: z.ZodMiniType<
  DeleteAssetPricingResponse,
  unknown
> = z.object({
  success: types.boolean(),
  deleted: types.boolean(),
});

export function deleteAssetPricingResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteAssetPricingResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteAssetPricingResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteAssetPricingResponse' from JSON`,
  );
}
