/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetAssetPricingRequest = {
  passportId: string;
};

/**
 * Pricing data (null if not configured)
 */
export type GetAssetPricingResponse = {
  success: boolean;
  pricing?: models.AssetPricing | null | undefined;
};

/** @internal */
export type GetAssetPricingRequest$Outbound = {
  passport_id: string;
};

/** @internal */
export const GetAssetPricingRequest$outboundSchema: z.ZodMiniType<
  GetAssetPricingRequest$Outbound,
  GetAssetPricingRequest
> = z.pipe(
  z.object({
    passportId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      passportId: "passport_id",
    });
  }),
);

export function getAssetPricingRequestToJSON(
  getAssetPricingRequest: GetAssetPricingRequest,
): string {
  return JSON.stringify(
    GetAssetPricingRequest$outboundSchema.parse(getAssetPricingRequest),
  );
}

/** @internal */
export const GetAssetPricingResponse$inboundSchema: z.ZodMiniType<
  GetAssetPricingResponse,
  unknown
> = z.object({
  success: types.boolean(),
  pricing: z.optional(z.nullable(models.AssetPricing$inboundSchema)),
});

export function getAssetPricingResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAssetPricingResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAssetPricingResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAssetPricingResponse' from JSON`,
  );
}
