/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetAssetRevenueRequest = {
  passportId: string;
  token?: string | undefined;
};

/**
 * Revenue summary
 */
export type GetAssetRevenueResponse = {
  success: boolean;
  revenue: models.RevenueInfo;
};

/** @internal */
export type GetAssetRevenueRequest$Outbound = {
  passport_id: string;
  token: string;
};

/** @internal */
export const GetAssetRevenueRequest$outboundSchema: z.ZodMiniType<
  GetAssetRevenueRequest$Outbound,
  GetAssetRevenueRequest
> = z.pipe(
  z.object({
    passportId: z.string(),
    token: z._default(z.string(), "USDC"),
  }),
  z.transform((v) => {
    return remap$(v, {
      passportId: "passport_id",
    });
  }),
);

export function getAssetRevenueRequestToJSON(
  getAssetRevenueRequest: GetAssetRevenueRequest,
): string {
  return JSON.stringify(
    GetAssetRevenueRequest$outboundSchema.parse(getAssetRevenueRequest),
  );
}

/** @internal */
export const GetAssetRevenueResponse$inboundSchema: z.ZodMiniType<
  GetAssetRevenueResponse,
  unknown
> = z.object({
  success: types.boolean(),
  revenue: models.RevenueInfo$inboundSchema,
});

export function getAssetRevenueResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAssetRevenueResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAssetRevenueResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAssetRevenueResponse' from JSON`,
  );
}
