/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Payment configuration
 */
export type GetPaymentConfigResponse = {
  success: boolean;
  config: { [k: string]: any };
};

/** @internal */
export const GetPaymentConfigResponse$inboundSchema: z.ZodMiniType<
  GetPaymentConfigResponse,
  unknown
> = z.object({
  success: types.boolean(),
  config: z.record(z.string(), z.any()),
});

export function getPaymentConfigResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetPaymentConfigResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPaymentConfigResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPaymentConfigResponse' from JSON`,
  );
}
