/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Chain = {
  chain?: string | undefined;
  tokens?: Array<string> | undefined;
};

/**
 * Supported chains
 */
export type GetSupportedChainsResponse = {
  success: boolean;
  chains: Array<Chain>;
};

/** @internal */
export const Chain$inboundSchema: z.ZodMiniType<Chain, unknown> = z.object({
  chain: types.optional(types.string()),
  tokens: types.optional(z.array(types.string())),
});

export function chainFromJSON(
  jsonString: string,
): SafeParseResult<Chain, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Chain$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Chain' from JSON`,
  );
}

/** @internal */
export const GetSupportedChainsResponse$inboundSchema: z.ZodMiniType<
  GetSupportedChainsResponse,
  unknown
> = z.object({
  success: types.boolean(),
  chains: z.array(z.lazy(() => Chain$inboundSchema)),
});

export function getSupportedChainsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetSupportedChainsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSupportedChainsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSupportedChainsResponse' from JSON`,
  );
}
