/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type LucidListZkmlModelsRequest = {
  chainId: string;
};

/** @internal */
export type LucidListZkmlModelsRequest$Outbound = {
  chainId: string;
};

/** @internal */
export const LucidListZkmlModelsRequest$outboundSchema: z.ZodMiniType<
  LucidListZkmlModelsRequest$Outbound,
  LucidListZkmlModelsRequest
> = z.object({
  chainId: z.string(),
});

export function lucidListZkmlModelsRequestToJSON(
  lucidListZkmlModelsRequest: LucidListZkmlModelsRequest,
): string {
  return JSON.stringify(
    LucidListZkmlModelsRequest$outboundSchema.parse(lucidListZkmlModelsRequest),
  );
}
