/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type LucidCommitEpochRootRequest = {
  projectId?: string | undefined;
  epochId?: string | undefined;
  force?: boolean | undefined;
};

/** @internal */
export type LucidCommitEpochRootRequest$Outbound = {
  project_id?: string | undefined;
  epoch_id?: string | undefined;
  force?: boolean | undefined;
};

/** @internal */
export const LucidCommitEpochRootRequest$outboundSchema: z.ZodMiniType<
  LucidCommitEpochRootRequest$Outbound,
  LucidCommitEpochRootRequest
> = z.pipe(
  z.object({
    projectId: z.optional(z.string()),
    epochId: z.optional(z.string()),
    force: z.optional(z.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      projectId: "project_id",
      epochId: "epoch_id",
    });
  }),
);

export function lucidCommitEpochRootRequestToJSON(
  lucidCommitEpochRootRequest: LucidCommitEpochRootRequest,
): string {
  return JSON.stringify(
    LucidCommitEpochRootRequest$outboundSchema.parse(
      lucidCommitEpochRootRequest,
    ),
  );
}
