/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type LucidRouteRequest = {
  modelMeta?: { [k: string]: any } | undefined;
  policy?: models.Policy | undefined;
  computeCatalog?: Array<{ [k: string]: any }> | undefined;
  requestId?: string | undefined;
  requireLiveHealthy?: boolean | undefined;
};

/** @internal */
export type LucidRouteRequest$Outbound = {
  model_meta?: { [k: string]: any } | undefined;
  policy?: models.Policy$Outbound | undefined;
  compute_catalog?: Array<{ [k: string]: any }> | undefined;
  request_id?: string | undefined;
  require_live_healthy: boolean;
};

/** @internal */
export const LucidRouteRequest$outboundSchema: z.ZodMiniType<
  LucidRouteRequest$Outbound,
  LucidRouteRequest
> = z.pipe(
  z.object({
    modelMeta: z.optional(z.record(z.string(), z.any())),
    policy: z.optional(models.Policy$outboundSchema),
    computeCatalog: z.optional(z.array(z.record(z.string(), z.any()))),
    requestId: z.optional(z.string()),
    requireLiveHealthy: z._default(z.boolean(), true),
  }),
  z.transform((v) => {
    return remap$(v, {
      modelMeta: "model_meta",
      computeCatalog: "compute_catalog",
      requestId: "request_id",
      requireLiveHealthy: "require_live_healthy",
    });
  }),
);

export function lucidRouteRequestToJSON(
  lucidRouteRequest: LucidRouteRequest,
): string {
  return JSON.stringify(
    LucidRouteRequest$outboundSchema.parse(lucidRouteRequest),
  );
}
