/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type LucidMatchExplainRequest = {
  policy?: models.Policy | undefined;
  computeMeta?: { [k: string]: any } | undefined;
  modelMeta?: { [k: string]: any } | undefined;
};

/** @internal */
export type LucidMatchExplainRequest$Outbound = {
  policy?: models.Policy$Outbound | undefined;
  compute_meta?: { [k: string]: any } | undefined;
  model_meta?: { [k: string]: any } | undefined;
};

/** @internal */
export const LucidMatchExplainRequest$outboundSchema: z.ZodMiniType<
  LucidMatchExplainRequest$Outbound,
  LucidMatchExplainRequest
> = z.pipe(
  z.object({
    policy: z.optional(models.Policy$outboundSchema),
    computeMeta: z.optional(z.record(z.string(), z.any())),
    modelMeta: z.optional(z.record(z.string(), z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      computeMeta: "compute_meta",
      modelMeta: "model_meta",
    });
  }),
);

export function lucidMatchExplainRequestToJSON(
  lucidMatchExplainRequest: LucidMatchExplainRequest,
): string {
  return JSON.stringify(
    LucidMatchExplainRequest$outboundSchema.parse(lucidMatchExplainRequest),
  );
}
