/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type LucidVerifyPayoutRequest = {
  runId: string;
};

/** @internal */
export type LucidVerifyPayoutRequest$Outbound = {
  run_id: string;
};

/** @internal */
export const LucidVerifyPayoutRequest$outboundSchema: z.ZodMiniType<
  LucidVerifyPayoutRequest$Outbound,
  LucidVerifyPayoutRequest
> = z.pipe(
  z.object({
    runId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      runId: "run_id",
    });
  }),
);

export function lucidVerifyPayoutRequestToJSON(
  lucidVerifyPayoutRequest: LucidVerifyPayoutRequest,
): string {
  return JSON.stringify(
    LucidVerifyPayoutRequest$outboundSchema.parse(lucidVerifyPayoutRequest),
  );
}
