/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type LucidGetEpochRequest = {
  epochId: string;
};

/** @internal */
export type LucidGetEpochRequest$Outbound = {
  epoch_id: string;
};

/** @internal */
export const LucidGetEpochRequest$outboundSchema: z.ZodMiniType<
  LucidGetEpochRequest$Outbound,
  LucidGetEpochRequest
> = z.pipe(
  z.object({
    epochId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      epochId: "epoch_id",
    });
  }),
);

export function lucidGetEpochRequestToJSON(
  lucidGetEpochRequest: LucidGetEpochRequest,
): string {
  return JSON.stringify(
    LucidGetEpochRequest$outboundSchema.parse(lucidGetEpochRequest),
  );
}
