/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type LucidRetryEpochRequest = {
  epochId: string;
};

/** @internal */
export type LucidRetryEpochRequest$Outbound = {
  epoch_id: string;
};

/** @internal */
export const LucidRetryEpochRequest$outboundSchema: z.ZodMiniType<
  LucidRetryEpochRequest$Outbound,
  LucidRetryEpochRequest
> = z.pipe(
  z.object({
    epochId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      epochId: "epoch_id",
    });
  }),
);

export function lucidRetryEpochRequestToJSON(
  lucidRetryEpochRequest: LucidRetryEpochRequest,
): string {
  return JSON.stringify(
    LucidRetryEpochRequest$outboundSchema.parse(lucidRetryEpochRequest),
  );
}
