/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type LucidListEpochsRequest = {
  projectId?: string | undefined;
  status?: string | undefined;
  page?: number | undefined;
  perPage?: number | undefined;
};

/** @internal */
export type LucidListEpochsRequest$Outbound = {
  project_id?: string | undefined;
  status?: string | undefined;
  page?: number | undefined;
  per_page?: number | undefined;
};

/** @internal */
export const LucidListEpochsRequest$outboundSchema: z.ZodMiniType<
  LucidListEpochsRequest$Outbound,
  LucidListEpochsRequest
> = z.pipe(
  z.object({
    projectId: z.optional(z.string()),
    status: z.optional(z.string()),
    page: z.optional(z.int()),
    perPage: z.optional(z.int()),
  }),
  z.transform((v) => {
    return remap$(v, {
      projectId: "project_id",
      perPage: "per_page",
    });
  }),
);

export function lucidListEpochsRequestToJSON(
  lucidListEpochsRequest: LucidListEpochsRequest,
): string {
  return JSON.stringify(
    LucidListEpochsRequest$outboundSchema.parse(lucidListEpochsRequest),
  );
}
