/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type LucidGetEpochTransactionRequest = {
  epochId: string;
};

/** @internal */
export type LucidGetEpochTransactionRequest$Outbound = {
  epoch_id: string;
};

/** @internal */
export const LucidGetEpochTransactionRequest$outboundSchema: z.ZodMiniType<
  LucidGetEpochTransactionRequest$Outbound,
  LucidGetEpochTransactionRequest
> = z.pipe(
  z.object({
    epochId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      epochId: "epoch_id",
    });
  }),
);

export function lucidGetEpochTransactionRequestToJSON(
  lucidGetEpochTransactionRequest: LucidGetEpochTransactionRequest,
): string {
  return JSON.stringify(
    LucidGetEpochTransactionRequest$outboundSchema.parse(
      lucidGetEpochTransactionRequest,
    ),
  );
}
