/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type LucidSearchComputeRequest = {
  regions?: string | undefined;
  runtimes?: string | undefined;
  providerType?: string | undefined;
  minVram?: number | undefined;
  gpu?: string | undefined;
  owner?: string | undefined;
  tags?: string | undefined;
  search?: string | undefined;
  page?: number | undefined;
  perPage?: number | undefined;
};

/** @internal */
export type LucidSearchComputeRequest$Outbound = {
  regions?: string | undefined;
  runtimes?: string | undefined;
  provider_type?: string | undefined;
  min_vram?: number | undefined;
  gpu?: string | undefined;
  owner?: string | undefined;
  tags?: string | undefined;
  search?: string | undefined;
  page?: number | undefined;
  per_page?: number | undefined;
};

/** @internal */
export const LucidSearchComputeRequest$outboundSchema: z.ZodMiniType<
  LucidSearchComputeRequest$Outbound,
  LucidSearchComputeRequest
> = z.pipe(
  z.object({
    regions: z.optional(z.string()),
    runtimes: z.optional(z.string()),
    providerType: z.optional(z.string()),
    minVram: z.optional(z.int()),
    gpu: z.optional(z.string()),
    owner: z.optional(z.string()),
    tags: z.optional(z.string()),
    search: z.optional(z.string()),
    page: z.optional(z.int()),
    perPage: z.optional(z.int()),
  }),
  z.transform((v) => {
    return remap$(v, {
      providerType: "provider_type",
      minVram: "min_vram",
      perPage: "per_page",
    });
  }),
);

export function lucidSearchComputeRequestToJSON(
  lucidSearchComputeRequest: LucidSearchComputeRequest,
): string {
  return JSON.stringify(
    LucidSearchComputeRequest$outboundSchema.parse(lucidSearchComputeRequest),
  );
}
