/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type LucidMatchRequest = {
  modelMeta?: { [k: string]: any } | undefined;
  policy?: models.Policy | undefined;
  computeCatalog?: Array<{ [k: string]: any }> | undefined;
  requireLiveHealthy?: boolean | undefined;
};

/** @internal */
export type LucidMatchRequest$Outbound = {
  model_meta?: { [k: string]: any } | undefined;
  policy?: models.Policy$Outbound | undefined;
  compute_catalog?: Array<{ [k: string]: any }> | undefined;
  require_live_healthy: boolean;
};

/** @internal */
export const LucidMatchRequest$outboundSchema: z.ZodMiniType<
  LucidMatchRequest$Outbound,
  LucidMatchRequest
> = z.pipe(
  z.object({
    modelMeta: z.optional(z.record(z.string(), z.any())),
    policy: z.optional(models.Policy$outboundSchema),
    computeCatalog: z.optional(z.array(z.record(z.string(), z.any()))),
    requireLiveHealthy: z._default(z.boolean(), true),
  }),
  z.transform((v) => {
    return remap$(v, {
      modelMeta: "model_meta",
      computeCatalog: "compute_catalog",
      requireLiveHealthy: "require_live_healthy",
    });
  }),
);

export function lucidMatchRequestToJSON(
  lucidMatchRequest: LucidMatchRequest,
): string {
  return JSON.stringify(
    LucidMatchRequest$outboundSchema.parse(lucidMatchRequest),
  );
}
