/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type LucidGetPayoutRequest = {
  runId: string;
};

/** @internal */
export type LucidGetPayoutRequest$Outbound = {
  run_id: string;
};

/** @internal */
export const LucidGetPayoutRequest$outboundSchema: z.ZodMiniType<
  LucidGetPayoutRequest$Outbound,
  LucidGetPayoutRequest
> = z.pipe(
  z.object({
    runId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      runId: "run_id",
    });
  }),
);

export function lucidGetPayoutRequestToJSON(
  lucidGetPayoutRequest: LucidGetPayoutRequest,
): string {
  return JSON.stringify(
    LucidGetPayoutRequest$outboundSchema.parse(lucidGetPayoutRequest),
  );
}
