/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type LucidCommitEpochRootsBatchRequest = {
  epochIds: Array<string>;
};

/** @internal */
export type LucidCommitEpochRootsBatchRequest$Outbound = {
  epoch_ids: Array<string>;
};

/** @internal */
export const LucidCommitEpochRootsBatchRequest$outboundSchema: z.ZodMiniType<
  LucidCommitEpochRootsBatchRequest$Outbound,
  LucidCommitEpochRootsBatchRequest
> = z.pipe(
  z.object({
    epochIds: z.array(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      epochIds: "epoch_ids",
    });
  }),
);

export function lucidCommitEpochRootsBatchRequestToJSON(
  lucidCommitEpochRootsBatchRequest: LucidCommitEpochRootsBatchRequest,
): string {
  return JSON.stringify(
    LucidCommitEpochRootsBatchRequest$outboundSchema.parse(
      lucidCommitEpochRootsBatchRequest,
    ),
  );
}
