/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type LucidCreateEpochRequest = {
  projectId?: string | undefined;
};

/** @internal */
export type LucidCreateEpochRequest$Outbound = {
  project_id?: string | undefined;
};

/** @internal */
export const LucidCreateEpochRequest$outboundSchema: z.ZodMiniType<
  LucidCreateEpochRequest$Outbound,
  LucidCreateEpochRequest
> = z.pipe(
  z.object({
    projectId: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      projectId: "project_id",
    });
  }),
);

export function lucidCreateEpochRequestToJSON(
  lucidCreateEpochRequest: LucidCreateEpochRequest,
): string {
  return JSON.stringify(
    LucidCreateEpochRequest$outboundSchema.parse(lucidCreateEpochRequest),
  );
}
