/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type LucidVerifyEpochRequest = {
  epochId: string;
};

/** @internal */
export type LucidVerifyEpochRequest$Outbound = {
  epoch_id: string;
};

/** @internal */
export const LucidVerifyEpochRequest$outboundSchema: z.ZodMiniType<
  LucidVerifyEpochRequest$Outbound,
  LucidVerifyEpochRequest
> = z.pipe(
  z.object({
    epochId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      epochId: "epoch_id",
    });
  }),
);

export function lucidVerifyEpochRequestToJSON(
  lucidVerifyEpochRequest: LucidVerifyEpochRequest,
): string {
  return JSON.stringify(
    LucidVerifyEpochRequest$outboundSchema.parse(lucidVerifyEpochRequest),
  );
}
