/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type SetAssetPricingRequest = {
  passportId: string;
  body: models.SetAssetPricingRequest;
};

/** @internal */
export type SetAssetPricingRequest$Outbound = {
  passport_id: string;
  body: models.SetAssetPricingRequest$Outbound;
};

/** @internal */
export const SetAssetPricingRequest$outboundSchema: z.ZodMiniType<
  SetAssetPricingRequest$Outbound,
  SetAssetPricingRequest
> = z.pipe(
  z.object({
    passportId: z.string(),
    body: models.SetAssetPricingRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      passportId: "passport_id",
    });
  }),
);

export function setAssetPricingRequestToJSON(
  setAssetPricingRequest: SetAssetPricingRequest,
): string {
  return JSON.stringify(
    SetAssetPricingRequest$outboundSchema.parse(setAssetPricingRequest),
  );
}
