/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const Facilitator = {
  Direct: "direct",
  Coinbase: "coinbase",
  Payai: "payai",
} as const;
export type Facilitator = ClosedEnum<typeof Facilitator>;

export type SetDefaultFacilitatorRequest = {
  facilitator: Facilitator;
};

/** @internal */
export const Facilitator$outboundSchema: z.ZodMiniEnum<typeof Facilitator> = z
  .enum(Facilitator);

/** @internal */
export type SetDefaultFacilitatorRequest$Outbound = {
  facilitator: string;
};

/** @internal */
export const SetDefaultFacilitatorRequest$outboundSchema: z.ZodMiniType<
  SetDefaultFacilitatorRequest$Outbound,
  SetDefaultFacilitatorRequest
> = z.object({
  facilitator: Facilitator$outboundSchema,
});

export function setDefaultFacilitatorRequestToJSON(
  setDefaultFacilitatorRequest: SetDefaultFacilitatorRequest,
): string {
  return JSON.stringify(
    SetDefaultFacilitatorRequest$outboundSchema.parse(
      setDefaultFacilitatorRequest,
    ),
  );
}
