/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SubscribeRequestBody = {
  passportId: string;
  durationHours?: number | undefined;
};

export type SubscribeRequest = {
  /**
   * Transaction hash proving USDC payment (x402 protocol)
   */
  xPaymentProof: string;
  body: SubscribeRequestBody;
};

/**
 * Subscription created
 */
export type SubscribeResponse = {
  subscribed: boolean;
  passportId: string;
  /**
   * Unix timestamp
   */
  expiresAt: number;
  durationHours: number;
};

/** @internal */
export type SubscribeRequestBody$Outbound = {
  passport_id: string;
  duration_hours: number;
};

/** @internal */
export const SubscribeRequestBody$outboundSchema: z.ZodMiniType<
  SubscribeRequestBody$Outbound,
  SubscribeRequestBody
> = z.pipe(
  z.object({
    passportId: z.string(),
    durationHours: z._default(z.int(), 24),
  }),
  z.transform((v) => {
    return remap$(v, {
      passportId: "passport_id",
      durationHours: "duration_hours",
    });
  }),
);

export function subscribeRequestBodyToJSON(
  subscribeRequestBody: SubscribeRequestBody,
): string {
  return JSON.stringify(
    SubscribeRequestBody$outboundSchema.parse(subscribeRequestBody),
  );
}

/** @internal */
export type SubscribeRequest$Outbound = {
  "X-Payment-Proof": string;
  body: SubscribeRequestBody$Outbound;
};

/** @internal */
export const SubscribeRequest$outboundSchema: z.ZodMiniType<
  SubscribeRequest$Outbound,
  SubscribeRequest
> = z.pipe(
  z.object({
    xPaymentProof: z.string(),
    body: z.lazy(() => SubscribeRequestBody$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      xPaymentProof: "X-Payment-Proof",
    });
  }),
);

export function subscribeRequestToJSON(
  subscribeRequest: SubscribeRequest,
): string {
  return JSON.stringify(
    SubscribeRequest$outboundSchema.parse(subscribeRequest),
  );
}

/** @internal */
export const SubscribeResponse$inboundSchema: z.ZodMiniType<
  SubscribeResponse,
  unknown
> = z.pipe(
  z.object({
    subscribed: types.boolean(),
    passport_id: types.string(),
    expires_at: types.number(),
    duration_hours: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "passport_id": "passportId",
      "expires_at": "expiresAt",
      "duration_hours": "durationHours",
    });
  }),
);

export function subscribeResponseFromJSON(
  jsonString: string,
): SafeParseResult<SubscribeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SubscribeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SubscribeResponse' from JSON`,
  );
}
