/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type WithdrawAssetRevenueRequestBody = {
  token?: string | undefined;
};

export type WithdrawAssetRevenueRequest = {
  passportId: string;
  body?: WithdrawAssetRevenueRequestBody | undefined;
};

export const WithdrawAssetRevenueStatus = {
  PendingPayout: "pending_payout",
  NoFunds: "no_funds",
} as const;
export type WithdrawAssetRevenueStatus = OpenEnum<
  typeof WithdrawAssetRevenueStatus
>;

export type Withdrawal = {
  /**
   * Amount in micro-units
   */
  amount: string;
  token: string;
  status: WithdrawAssetRevenueStatus;
};

/**
 * Withdrawal queued
 */
export type WithdrawAssetRevenueResponse = {
  success: boolean;
  withdrawal: Withdrawal;
};

/** @internal */
export type WithdrawAssetRevenueRequestBody$Outbound = {
  token: string;
};

/** @internal */
export const WithdrawAssetRevenueRequestBody$outboundSchema: z.ZodMiniType<
  WithdrawAssetRevenueRequestBody$Outbound,
  WithdrawAssetRevenueRequestBody
> = z.object({
  token: z._default(z.string(), "USDC"),
});

export function withdrawAssetRevenueRequestBodyToJSON(
  withdrawAssetRevenueRequestBody: WithdrawAssetRevenueRequestBody,
): string {
  return JSON.stringify(
    WithdrawAssetRevenueRequestBody$outboundSchema.parse(
      withdrawAssetRevenueRequestBody,
    ),
  );
}

/** @internal */
export type WithdrawAssetRevenueRequest$Outbound = {
  passport_id: string;
  body?: WithdrawAssetRevenueRequestBody$Outbound | undefined;
};

/** @internal */
export const WithdrawAssetRevenueRequest$outboundSchema: z.ZodMiniType<
  WithdrawAssetRevenueRequest$Outbound,
  WithdrawAssetRevenueRequest
> = z.pipe(
  z.object({
    passportId: z.string(),
    body: z.optional(
      z.lazy(() => WithdrawAssetRevenueRequestBody$outboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      passportId: "passport_id",
    });
  }),
);

export function withdrawAssetRevenueRequestToJSON(
  withdrawAssetRevenueRequest: WithdrawAssetRevenueRequest,
): string {
  return JSON.stringify(
    WithdrawAssetRevenueRequest$outboundSchema.parse(
      withdrawAssetRevenueRequest,
    ),
  );
}

/** @internal */
export const WithdrawAssetRevenueStatus$inboundSchema: z.ZodMiniType<
  WithdrawAssetRevenueStatus,
  unknown
> = openEnums.inboundSchema(WithdrawAssetRevenueStatus);

/** @internal */
export const Withdrawal$inboundSchema: z.ZodMiniType<Withdrawal, unknown> = z
  .object({
    amount: types.string(),
    token: types.string(),
    status: WithdrawAssetRevenueStatus$inboundSchema,
  });

export function withdrawalFromJSON(
  jsonString: string,
): SafeParseResult<Withdrawal, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Withdrawal$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Withdrawal' from JSON`,
  );
}

/** @internal */
export const WithdrawAssetRevenueResponse$inboundSchema: z.ZodMiniType<
  WithdrawAssetRevenueResponse,
  unknown
> = z.object({
  success: types.boolean(),
  withdrawal: z.lazy(() => Withdrawal$inboundSchema),
});

export function withdrawAssetRevenueResponseFromJSON(
  jsonString: string,
): SafeParseResult<WithdrawAssetRevenueResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WithdrawAssetRevenueResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WithdrawAssetRevenueResponse' from JSON`,
  );
}
