/** @deprecated Use `lucid launch --image` or `--runtime base` instead. This adapter will move to examples/ in a future release. */
// offchain/packages/engine/src/runtime/GoogleADKAdapter.ts
// Google ADK adapter — generates Python agent using Google's Agent Development Kit

import { IRuntimeAdapter, RuntimeArtifact } from './IRuntimeAdapter';

/**
 * Google ADK Adapter
 *
 * Generates Python code using Google's Agent Development Kit.
 * Native A2A + MCP support. Best for Google Cloud deployments.
 */
export class GoogleADKAdapter implements IRuntimeAdapter {
  readonly name = 'google-adk';
  readonly version = '1.0.0';
  readonly language = 'python' as const;

  canHandle(descriptor: any): boolean {
    return true;
  }

  async generate(descriptor: any, passportId: string): Promise<RuntimeArtifact> {
    const config = descriptor.agent_config;
    const files = new Map<string, string>();

    files.set('agent.py', `"""
Lucid Agent: ${passportId}
Generated by Lucid-L2 Google ADK Adapter
"""
import os
import json
import httpx
from google.adk.agents import Agent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.adk.tools import FunctionTool

MCPGATE_URL = os.environ.get("MCPGATE_URL", "https://mcpgate-api-production.up.railway.app")
MCPGATE_API_KEY = os.environ.get("MCPGATE_API_KEY", "")


def call_mcp_tool(server: str, tool_name: str, arguments: str) -> str:
    """Call an MCP tool through Lucid MCPGate."""
    resp = httpx.post(
        f"{MCPGATE_URL}/v1/tools/call",
        headers={"Authorization": f"Bearer {MCPGATE_API_KEY}", "Content-Type": "application/json"},
        json={"server": server, "tool": tool_name, "arguments": json.loads(arguments)},
        timeout=30.0,
    )
    resp.raise_for_status()
    return json.dumps(resp.json())


agent = Agent(
    model="${config.model_passport_id}",
    name="${passportId}",
    instruction=${JSON.stringify(config.system_prompt)},
    tools=[FunctionTool(call_mcp_tool)],
)

session_service = InMemorySessionService()
runner = Runner(agent=agent, app_name="${passportId}", session_service=session_service)


# --- HTTP Server ---
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(title=f"Lucid Agent: ${passportId}")


class RunRequest(BaseModel):
    prompt: str
    session_id: str = "default"
    user_id: str = "user"


@app.get("/health")
async def health():
    return {"status": "healthy", "agent": "${passportId}", "adapter": "google-adk"}


@app.post("/run")
async def run_agent(req: RunRequest):
    try:
        session = await session_service.create_session(
            app_name="${passportId}", user_id=req.user_id
        )
        from google.adk.content import Content, Part
        content = Content(role="user", parts=[Part.from_text(req.prompt)])

        response_text = ""
        async for event in runner.run_async(
            user_id=req.user_id, session_id=session.id, new_message=content
        ):
            if hasattr(event, "content") and event.content and event.content.parts:
                for part in event.content.parts:
                    if hasattr(part, "text") and part.text:
                        response_text += part.text

        return {"ok": True, "text": response_text}
    except Exception as e:
        return {"ok": False, "error": str(e)}


if __name__ == "__main__":
    import uvicorn
    port = int(os.environ.get("PORT", "3100"))
    uvicorn.run(app, host="0.0.0.0", port=port)
`);

    files.set('requirements.txt', `google-adk>=0.3.0
httpx>=0.27.0
fastapi>=0.109.0
uvicorn>=0.27.0
`);

    const dockerfile = `FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 3100
CMD ["python", "agent.py"]
`;
    files.set('Dockerfile', dockerfile);

    return {
      adapter: this.name,
      files,
      entrypoint: 'agent.py',
      dependencies: { 'google-adk': '>=0.3.0', 'httpx': '>=0.27.0', 'fastapi': '>=0.109.0' },
      env_vars: { MCPGATE_URL: '', MCPGATE_API_KEY: '', GOOGLE_API_KEY: '', PORT: '3100' },
      dockerfile,
    };
  }
}
