/** @deprecated Use `lucid launch --image` or `--runtime base` instead. This adapter will move to examples/ in a future release. */
// offchain/packages/engine/src/runtime/LangGraphAdapter.ts
// LangGraph adapter — generates Python StateGraph code for LangChain/LangGraph

import { IRuntimeAdapter, RuntimeArtifact } from './IRuntimeAdapter';

/**
 * LangGraph Adapter
 *
 * Generates Python StateGraph code for LangChain/LangGraph framework.
 * Best for complex workflows with loops, conditionals, and MCP tools.
 */
export class LangGraphAdapter implements IRuntimeAdapter {
  readonly name = 'langgraph';
  readonly version = '1.0.0';
  readonly language = 'python' as const;

  canHandle(descriptor: any): boolean {
    return true; // LangGraph handles all workflow types
  }

  async generate(descriptor: any, passportId: string): Promise<RuntimeArtifact> {
    const config = descriptor.agent_config;
    const files = new Map<string, string>();

    files.set('agent.py', `"""
Lucid Agent: ${passportId}
Generated by Lucid-L2 LangGraph Adapter
"""
import os
import json
import httpx
from typing import Annotated, TypedDict
from langgraph.prebuilt import create_react_agent
from langgraph.checkpoint.memory import MemorySaver
from langchain_openai import ChatOpenAI
from langchain_core.tools import tool

# --- Configuration ---
TRUSTGATE_URL = os.environ.get("TRUSTGATE_URL", "https://trustgate-api-production.up.railway.app")
TRUSTGATE_API_KEY = os.environ.get("TRUSTGATE_API_KEY", "")
MCPGATE_URL = os.environ.get("MCPGATE_URL", "https://mcpgate-api-production.up.railway.app")
MCPGATE_API_KEY = os.environ.get("MCPGATE_API_KEY", "")


# --- LLM (via TrustGate) ---
llm = ChatOpenAI(
    model="${config.model_passport_id}",
    temperature=${config.temperature || 0.7},
    max_tokens=${config.max_tokens || 4096},
    base_url=TRUSTGATE_URL + "/v1",
    api_key=TRUSTGATE_API_KEY,
)


# --- MCP Tool Bridge ---
@tool
def call_mcp_tool(server: str, tool_name: str, arguments: str) -> str:
    """Call an MCP tool through Lucid MCPGate.

    Args:
        server: MCP server name
        tool_name: Tool name
        arguments: JSON string of tool arguments
    """
    resp = httpx.post(
        f"{MCPGATE_URL}/v1/tools/call",
        headers={
            "Authorization": f"Bearer {MCPGATE_API_KEY}",
            "Content-Type": "application/json",
        },
        json={"server": server, "tool": tool_name, "arguments": json.loads(arguments)},
        timeout=30.0,
    )
    resp.raise_for_status()
    return json.dumps(resp.json())


# --- Agent ---
${config.memory_enabled ? 'checkpointer = MemorySaver()' : 'checkpointer = None'}

agent = create_react_agent(
    model=llm,
    tools=[call_mcp_tool],
    checkpointer=checkpointer,
)

# --- HTTP Server ---
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(title=f"Lucid Agent: ${passportId}")


class RunRequest(BaseModel):
    prompt: str
    thread_id: str = "default"


@app.get("/health")
async def health():
    return {"status": "healthy", "agent": "${passportId}", "adapter": "langgraph"}


@app.post("/run")
async def run_agent(req: RunRequest):
    try:
        config = {"configurable": {"thread_id": req.thread_id}}
        result = agent.invoke(
            {"messages": [("user", req.prompt)]},
            config=config,
        )
        last_message = result["messages"][-1]
        return {"ok": True, "text": last_message.content, "messages": len(result["messages"])}
    except Exception as e:
        return {"ok": False, "error": str(e)}


if __name__ == "__main__":
    import uvicorn
    port = int(os.environ.get("PORT", "3100"))
    uvicorn.run(app, host="0.0.0.0", port=port)
`);

    files.set('requirements.txt', `langgraph>=0.2.0
langchain-openai>=0.2.0
langchain-core>=0.3.0
httpx>=0.27.0
fastapi>=0.109.0
uvicorn>=0.27.0
`);

    const dockerfile = `FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 3100
HEALTHCHECK --interval=30s --timeout=5s CMD curl -f http://localhost:3100/health || exit 1
CMD ["python", "agent.py"]
`;
    files.set('Dockerfile', dockerfile);

    return {
      adapter: this.name,
      files,
      entrypoint: 'agent.py',
      dependencies: {
        'langgraph': '>=0.2.0',
        'langchain-openai': '>=0.2.0',
        'httpx': '>=0.27.0',
        'fastapi': '>=0.109.0',
      },
      env_vars: {
        TRUSTGATE_URL: '',
        TRUSTGATE_API_KEY: '',
        MCPGATE_URL: '',
        MCPGATE_API_KEY: '',
        PORT: '3100',
      },
      dockerfile,
    };
  }
}
