/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { computeGetNodeHealth } from "../funcs/computeGetNodeHealth.js";
import { computeHeartbeat } from "../funcs/computeHeartbeat.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Compute extends ClientSDK {
  /**
   * Submit compute node heartbeat
   */
  async heartbeat(
    request: models.ComputeHeartbeat,
    options?: RequestOptions,
  ): Promise<operations.LucidHeartbeatResponse> {
    return unwrapAsync(computeHeartbeat(
      this,
      request,
      options,
    ));
  }

  /**
   * Get compute node health
   */
  async getNodeHealth(
    request: operations.LucidGetHealthRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidGetHealthResponse> {
    return unwrapAsync(computeGetNodeHealth(
      this,
      request,
      options,
    ));
  }
}
