/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { disputesAppeal } from "../funcs/disputesAppeal.js";
import { disputesGet } from "../funcs/disputesGet.js";
import { disputesOpen } from "../funcs/disputesOpen.js";
import { disputesResolve } from "../funcs/disputesResolve.js";
import { disputesSubmitEvidence } from "../funcs/disputesSubmitEvidence.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Disputes extends ClientSDK {
  /**
   * Open a dispute on an escrow
   */
  async open(
    request: models.OpenDisputeRequest,
    options?: RequestOptions,
  ): Promise<models.SuccessResponse> {
    return unwrapAsync(disputesOpen(
      this,
      request,
      options,
    ));
  }

  /**
   * Submit evidence for a dispute
   */
  async submitEvidence(
    request: operations.LucidSubmitEvidenceRequest,
    options?: RequestOptions,
  ): Promise<models.SuccessResponse> {
    return unwrapAsync(disputesSubmitEvidence(
      this,
      request,
      options,
    ));
  }

  /**
   * Resolve a dispute
   */
  async resolve(
    request: operations.LucidResolveDisputeRequest,
    options?: RequestOptions,
  ): Promise<models.SuccessResponse> {
    return unwrapAsync(disputesResolve(
      this,
      request,
      options,
    ));
  }

  /**
   * Appeal a dispute decision
   */
  async appeal(
    request: operations.LucidAppealDisputeRequest,
    options?: RequestOptions,
  ): Promise<models.SuccessResponse> {
    return unwrapAsync(disputesAppeal(
      this,
      request,
      options,
    ));
  }

  /**
   * Get dispute details
   */
  async get(
    request: operations.LucidGetDisputeRequest,
    options?: RequestOptions,
  ): Promise<models.GetDisputeResponse> {
    return unwrapAsync(disputesGet(
      this,
      request,
      options,
    ));
  }
}
