/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { escrowCreate } from "../funcs/escrowCreate.js";
import { escrowDispute } from "../funcs/escrowDispute.js";
import { escrowGet } from "../funcs/escrowGet.js";
import { escrowRelease } from "../funcs/escrowRelease.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Escrow extends ClientSDK {
  /**
   * Create a time-locked escrow
   */
  async create(
    request: models.CreateEscrowRequest,
    options?: RequestOptions,
  ): Promise<models.SuccessResponse> {
    return unwrapAsync(escrowCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Release escrow with verified receipt
   */
  async release(
    request: models.ReleaseEscrowRequest,
    options?: RequestOptions,
  ): Promise<models.SuccessResponse> {
    return unwrapAsync(escrowRelease(
      this,
      request,
      options,
    ));
  }

  /**
   * Dispute an escrow
   */
  async dispute(
    request: models.DisputeEscrowRequest,
    options?: RequestOptions,
  ): Promise<models.SuccessResponse> {
    return unwrapAsync(escrowDispute(
      this,
      request,
      options,
    ));
  }

  /**
   * Get escrow details
   */
  async get(
    request: operations.LucidGetEscrowRequest,
    options?: RequestOptions,
  ): Promise<models.GetEscrowResponse> {
    return unwrapAsync(escrowGet(
      this,
      request,
      options,
    ));
  }
}
