/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { identityGet } from "../funcs/identityGet.js";
import { identityGetChains } from "../funcs/identityGetChains.js";
import { identityLink } from "../funcs/identityLink.js";
import { identityResolve } from "../funcs/identityResolve.js";
import { identityUnlink } from "../funcs/identityUnlink.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Identity extends ClientSDK {
  /**
   * Link addresses cross-chain
   */
  async link(
    request: models.LinkIdentityRequest,
    options?: RequestOptions,
  ): Promise<models.IdentityLinkResponse> {
    return unwrapAsync(identityLink(
      this,
      request,
      options,
    ));
  }

  /**
   * Resolve cross-chain identity
   */
  async resolve(
    request: models.ResolveIdentityRequest,
    options?: RequestOptions,
  ): Promise<models.SuccessResponse> {
    return unwrapAsync(identityResolve(
      this,
      request,
      options,
    ));
  }

  /**
   * Resolve identity (GET)
   */
  async get(
    request: operations.LucidGetIdentityRequest,
    options?: RequestOptions,
  ): Promise<models.SuccessResponse> {
    return unwrapAsync(identityGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Get linked chains for identity
   */
  async getChains(
    request: operations.LucidGetIdentityChainsRequest,
    options?: RequestOptions,
  ): Promise<models.IdentityChainsResponse> {
    return unwrapAsync(identityGetChains(
      this,
      request,
      options,
    ));
  }

  /**
   * Unlink a cross-chain address
   */
  async unlink(
    request: models.UnlinkIdentityRequest,
    options?: RequestOptions,
  ): Promise<models.SuccessResponse> {
    return unwrapAsync(identityUnlink(
      this,
      request,
      options,
    ));
  }
}
