/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { modulesConfigurePayout } from "../funcs/modulesConfigurePayout.js";
import { modulesConfigurePolicy } from "../funcs/modulesConfigurePolicy.js";
import { modulesInstall } from "../funcs/modulesInstall.js";
import { modulesList } from "../funcs/modulesList.js";
import { modulesUninstall } from "../funcs/modulesUninstall.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Modules extends ClientSDK {
  /**
   * Install module on smart account
   */
  async install(
    request: models.InstallModuleRequest,
    options?: RequestOptions,
  ): Promise<models.SuccessResponse> {
    return unwrapAsync(modulesInstall(
      this,
      request,
      options,
    ));
  }

  /**
   * Uninstall module from smart account
   */
  async uninstall(
    request: models.UninstallModuleRequest,
    options?: RequestOptions,
  ): Promise<models.SuccessResponse> {
    return unwrapAsync(modulesUninstall(
      this,
      request,
      options,
    ));
  }

  /**
   * Configure policy module
   */
  async configurePolicy(
    request: models.ConfigurePolicyRequest,
    options?: RequestOptions,
  ): Promise<models.SuccessResponse> {
    return unwrapAsync(modulesConfigurePolicy(
      this,
      request,
      options,
    ));
  }

  /**
   * Configure payout module
   */
  async configurePayout(
    request: models.ConfigurePayoutRequest,
    options?: RequestOptions,
  ): Promise<models.SuccessResponse> {
    return unwrapAsync(modulesConfigurePayout(
      this,
      request,
      options,
    ));
  }

  /**
   * List installed modules
   */
  async list(
    request: operations.LucidListModulesRequest,
    options?: RequestOptions,
  ): Promise<models.ListModulesResponse> {
    return unwrapAsync(modulesList(
      this,
      request,
      options,
    ));
  }
}
