/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { passportsCreate } from "../funcs/passportsCreate.js";
import { passportsDelete } from "../funcs/passportsDelete.js";
import { passportsGet } from "../funcs/passportsGet.js";
import { passportsGetStats } from "../funcs/passportsGetStats.js";
import { passportsList } from "../funcs/passportsList.js";
import { passportsListPendingSync } from "../funcs/passportsListPendingSync.js";
import { passportsSearchCompute } from "../funcs/passportsSearchCompute.js";
import { passportsSearchModels } from "../funcs/passportsSearchModels.js";
import { passportsSync } from "../funcs/passportsSync.js";
import { passportsUpdate } from "../funcs/passportsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Passports extends ClientSDK {
  /**
   * Create a passport
   */
  async create(
    request: models.CreatePassportRequest,
    options?: RequestOptions,
  ): Promise<models.CreatePassportResponse> {
    return unwrapAsync(passportsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * List passports
   */
  async list(
    request?: operations.LucidListPassportsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.ListPassportsResponse> {
    return unwrapAsync(passportsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a passport
   */
  async get(
    request: operations.LucidGetPassportRequest,
    options?: RequestOptions,
  ): Promise<models.GetPassportResponse> {
    return unwrapAsync(passportsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a passport
   */
  async update(
    request: operations.LucidUpdatePassportRequest,
    options?: RequestOptions,
  ): Promise<models.GetPassportResponse> {
    return unwrapAsync(passportsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a passport (soft delete)
   */
  async delete(
    request: operations.LucidDeletePassportRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidDeletePassportResponse> {
    return unwrapAsync(passportsDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Trigger on-chain sync for a passport
   */
  async sync(
    request: operations.LucidTriggerPassportSyncRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidTriggerPassportSyncResponse> {
    return unwrapAsync(passportsSync(
      this,
      request,
      options,
    ));
  }

  /**
   * Get passports pending sync
   */
  async listPendingSync(
    options?: RequestOptions,
  ): Promise<operations.LucidListPassportsPendingSyncResponse> {
    return unwrapAsync(passportsListPendingSync(
      this,
      options,
    ));
  }

  /**
   * Passport statistics
   */
  async getStats(
    options?: RequestOptions,
  ): Promise<models.PassportStatsResponse> {
    return unwrapAsync(passportsGetStats(
      this,
      options,
    ));
  }

  /**
   * Search model passports
   */
  async searchModels(
    request?: operations.LucidSearchModelsRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(passportsSearchModels(
      this,
      request,
      options,
    ));
  }

  /**
   * Search compute passports
   */
  async searchCompute(
    request?: operations.LucidSearchComputeRequest | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(passportsSearchCompute(
      this,
      request,
      options,
    ));
  }
}
