/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { paymasterEstimate } from "../funcs/paymasterEstimate.js";
import { paymasterGetRate } from "../funcs/paymasterGetRate.js";
import { paymasterSponsor } from "../funcs/paymasterSponsor.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Paymaster extends ClientSDK {
  /**
   * Sponsor a UserOp with $LUCID
   */
  async sponsor(
    request: models.SponsorUserOpRequest,
    options?: RequestOptions,
  ): Promise<models.SuccessResponse> {
    return unwrapAsync(paymasterSponsor(
      this,
      request,
      options,
    ));
  }

  /**
   * Get LUCID/ETH exchange rate
   */
  async getRate(
    request: operations.LucidGetPaymasterRateRequest,
    options?: RequestOptions,
  ): Promise<models.PaymasterRateResponse> {
    return unwrapAsync(paymasterGetRate(
      this,
      request,
      options,
    ));
  }

  /**
   * Estimate gas cost in $LUCID
   */
  async estimate(
    request: models.EstimateGasRequest,
    options?: RequestOptions,
  ): Promise<models.SuccessResponse> {
    return unwrapAsync(paymasterEstimate(
      this,
      request,
      options,
    ));
  }
}
