/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { paymentsDeleteAssetPricing } from "../funcs/paymentsDeleteAssetPricing.js";
import { paymentsGetAssetPricing } from "../funcs/paymentsGetAssetPricing.js";
import { paymentsGetAssetRevenue } from "../funcs/paymentsGetAssetRevenue.js";
import { paymentsGetPaymentConfig } from "../funcs/paymentsGetPaymentConfig.js";
import { paymentsGetSupportedChains } from "../funcs/paymentsGetSupportedChains.js";
import { paymentsSetAssetPricing } from "../funcs/paymentsSetAssetPricing.js";
import { paymentsSetDefaultFacilitator } from "../funcs/paymentsSetDefaultFacilitator.js";
import { paymentsSubscribe } from "../funcs/paymentsSubscribe.js";
import { paymentsWithdrawAssetRevenue } from "../funcs/paymentsWithdrawAssetRevenue.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Payments extends ClientSDK {
  /**
   * Get asset pricing
   */
  async getAssetPricing(
    request: operations.GetAssetPricingRequest,
    options?: RequestOptions,
  ): Promise<operations.GetAssetPricingResponse> {
    return unwrapAsync(paymentsGetAssetPricing(
      this,
      request,
      options,
    ));
  }

  /**
   * Set asset pricing
   *
   * @remarks
   * Admin-only. Sets or updates the pricing configuration for an AI asset.
   */
  async setAssetPricing(
    request: operations.SetAssetPricingRequest,
    options?: RequestOptions,
  ): Promise<models.SuccessResponse> {
    return unwrapAsync(paymentsSetAssetPricing(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove asset pricing
   *
   * @remarks
   * Admin-only. Removes pricing (asset becomes free access).
   */
  async deleteAssetPricing(
    request: operations.DeleteAssetPricingRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteAssetPricingResponse> {
    return unwrapAsync(paymentsDeleteAssetPricing(
      this,
      request,
      options,
    ));
  }

  /**
   * Get asset revenue summary
   */
  async getAssetRevenue(
    request: operations.GetAssetRevenueRequest,
    options?: RequestOptions,
  ): Promise<operations.GetAssetRevenueResponse> {
    return unwrapAsync(paymentsGetAssetRevenue(
      this,
      request,
      options,
    ));
  }

  /**
   * Withdraw asset revenue
   *
   * @remarks
   * Admin-only. Marks confirmed revenue as pending_payout. The actual
   * on-chain transfer happens via the batch payout epoch.
   */
  async withdrawAssetRevenue(
    request: operations.WithdrawAssetRevenueRequest,
    options?: RequestOptions,
  ): Promise<operations.WithdrawAssetRevenueResponse> {
    return unwrapAsync(paymentsWithdrawAssetRevenue(
      this,
      request,
      options,
    ));
  }

  /**
   * Get x402 payment configuration
   */
  async getPaymentConfig(
    options?: RequestOptions,
  ): Promise<operations.GetPaymentConfigResponse> {
    return unwrapAsync(paymentsGetPaymentConfig(
      this,
      options,
    ));
  }

  /**
   * Set default payment facilitator
   *
   * @remarks
   * Admin-only. Sets the default x402 facilitator (direct, coinbase, payai).
   */
  async setDefaultFacilitator(
    request: operations.SetDefaultFacilitatorRequest,
    options?: RequestOptions,
  ): Promise<models.SuccessResponse> {
    return unwrapAsync(paymentsSetDefaultFacilitator(
      this,
      request,
      options,
    ));
  }

  /**
   * List supported payment chains
   */
  async getSupportedChains(
    options?: RequestOptions,
  ): Promise<operations.GetSupportedChainsResponse> {
    return unwrapAsync(paymentsGetSupportedChains(
      this,
      options,
    ));
  }

  /**
   * Subscribe to asset access
   *
   * @remarks
   * x402-gated. Pay via USDC and receive a time-limited access subscription.
   * On success, creates an on-chain AccessReceipt.
   */
  async subscribe(
    request: operations.SubscribeRequest,
    options?: RequestOptions,
  ): Promise<operations.SubscribeResponse> {
    return unwrapAsync(paymentsSubscribe(
      this,
      request,
      options,
    ));
  }
}
