/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sharesLucidGetShareToken } from "../funcs/sharesLucidGetShareToken.js";
import { sharesLucidLaunchShareToken } from "../funcs/sharesLucidLaunchShareToken.js";
import { sharesLucidTriggerRevenueAirdrop } from "../funcs/sharesLucidTriggerRevenueAirdrop.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Shares extends ClientSDK {
  /**
   * Launch a share token for a passport
   */
  async lucidLaunchShareToken(
    request: operations.LucidLaunchShareTokenRequest,
    options?: RequestOptions,
  ): Promise<models.TokenLaunchResponse> {
    return unwrapAsync(sharesLucidLaunchShareToken(
      this,
      request,
      options,
    ));
  }

  /**
   * Get share token info for a passport
   */
  async lucidGetShareToken(
    request: operations.LucidGetShareTokenRequest,
    options?: RequestOptions,
  ): Promise<models.TokenInfo> {
    return unwrapAsync(sharesLucidGetShareToken(
      this,
      request,
      options,
    ));
  }

  /**
   * Trigger revenue airdrop for share token holders
   */
  async lucidTriggerRevenueAirdrop(
    request: operations.LucidTriggerRevenueAirdropRequest,
    options?: RequestOptions,
  ): Promise<models.AirdropResponse> {
    return unwrapAsync(sharesLucidTriggerRevenueAirdrop(
      this,
      request,
      options,
    ));
  }
}
