/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tbaCreate } from "../funcs/tbaCreate.js";
import { tbaGet } from "../funcs/tbaGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Tba extends ClientSDK {
  /**
   * Create TBA for passport NFT
   */
  async create(
    request: models.CreateTBARequest,
    options?: RequestOptions,
  ): Promise<models.GetTBAResponse> {
    return unwrapAsync(tbaCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get TBA address
   */
  async get(
    request: operations.LucidGetTbaRequest,
    options?: RequestOptions,
  ): Promise<models.GetTBAResponse> {
    return unwrapAsync(tbaGet(
      this,
      request,
      options,
    ));
  }
}
