/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { zkMLListModels } from "../funcs/zkMLListModels.js";
import { zkMLProve } from "../funcs/zkMLProve.js";
import { zkMLRegisterModel } from "../funcs/zkMLRegisterModel.js";
import { zkMLVerify } from "../funcs/zkMLVerify.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ZkML extends ClientSDK {
  /**
   * Generate zkML proof
   */
  async prove(
    request: models.GenerateZkMLProofRequest,
    options?: RequestOptions,
  ): Promise<operations.LucidGenerateZkmlProofResponse> {
    return unwrapAsync(zkMLProve(
      this,
      request,
      options,
    ));
  }

  /**
   * Verify zkML proof
   */
  async verify(
    request: models.VerifyZkMLProofRequest,
    options?: RequestOptions,
  ): Promise<models.ZkMLVerifyResponse> {
    return unwrapAsync(zkMLVerify(
      this,
      request,
      options,
    ));
  }

  /**
   * Register model circuit
   */
  async registerModel(
    request: models.RegisterZkMLModelRequest,
    options?: RequestOptions,
  ): Promise<models.SuccessResponse> {
    return unwrapAsync(zkMLRegisterModel(
      this,
      request,
      options,
    ));
  }

  /**
   * List registered model circuits
   */
  async listModels(
    request: operations.LucidListZkmlModelsRequest,
    options?: RequestOptions,
  ): Promise<models.ListZkMLModelsResponse> {
    return unwrapAsync(zkMLListModels(
      this,
      request,
      options,
    ));
  }
}
