http:
  routers:
    api-lucid:
      rule: "Host(`api.lucid.foundation`)"
      entryPoints:
        - websecure
      service: offchain-api
      tls: {}
      priority: 1

  services:
    offchain-api:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3001"

tls:
  certificates:
    - certFile: /etc/letsencrypt/live/api.lucid.foundation/fullchain.pem
      keyFile: /etc/letsencrypt/live/api.lucid.foundation/privkey.pem
