/**
 * Vercel AI SDK provider for Lucid.
 *
 * This file is NOT generated by Speakeasy — it is safe to edit.
 *
 * @example
 * ```typescript
 * import { createLucidProvider } from 'raijin-labs-lucid-ai/ai';
 * import { streamText, generateText } from 'ai';
 *
 * const lucid = createLucidProvider({ apiKey: 'sk-...' });
 *
 * // Streaming
 * const stream = streamText({
 *   model: lucid('deepseek-v3'),
 *   messages: [{ role: 'user', content: 'Hello' }],
 * });
 *
 * // Non-streaming
 * const { text } = await generateText({
 *   model: lucid('gpt-4o'),
 *   prompt: 'Hello',
 * });
 * ```
 */

import { createOpenAICompatible } from "@ai-sdk/openai-compatible";

import { ServerList } from "./lib/config.js";

const DEFAULT_BASE_URL = ServerList[0] ?? "https://api.lucid.foundation";

export interface LucidProviderSettings {
  /**
   * Lucid API key. Falls back to the `LUCID_API_KEY` environment variable.
   */
  apiKey?: string;

  /**
   * Base URL for the Lucid API.
   * @default "https://api.lucid.foundation"
   */
  baseURL?: string;
}

/**
 * Create a Vercel AI SDK–compatible provider backed by Lucid.
 *
 * The returned provider can be used with `generateText`, `streamText`,
 * `generateObject`, `streamObject`, and any other Vercel AI SDK function.
 *
 * @deprecated Use `@lucid-l2/sdk` instead. This Speakeasy-generated HTTP SDK
 * is deprecated in favour of the embeddable SDK at `offchain/packages/sdk/`.
 * See https://github.com/raijinlabs/Lucid-L2 for migration details.
 */
export function createLucidProvider(options: LucidProviderSettings = {}) {
  const env = typeof globalThis !== "undefined" ? (globalThis as any).process?.env : undefined;
  const apiKey = options.apiKey ?? env?.LUCID_API_KEY ?? "";

  const baseURL = options.baseURL
    ? options.baseURL.replace(/\/+$/, "")
    : DEFAULT_BASE_URL;

  return createOpenAICompatible({
    name: "lucid",
    apiKey,
    baseURL: baseURL.endsWith("/v1") ? baseURL : `${baseURL}/v1`,
  });
}

/**
 * Default Lucid provider instance.
 *
 * Uses `LUCID_API_KEY` from environment and the default production URL.
 */
export const lucid = createLucidProvider();
