/**
 * Typed factory for LucidSDK with default chain support.
 *
 * This file is NOT generated by Speakeasy — it is safe to edit.
 *
 * @example
 * ```typescript
 * import { createLucidSDK } from '@lucid/sdk/lucid';
 *
 * const sdk = createLucidSDK({
 *   apiKey: 'lk_live_...',
 *   chain: 'base',
 * });
 *
 * // Chain auto-injected into v2 calls
 * await sdk.escrow.create({ beneficiary: '0x...', token: '0x...', amount: '100', duration: 3600 });
 *
 * // Override per call
 * await sdk.escrow.create({ chainId: 'ethereum-sepolia', beneficiary: '0x...', token: '0x...', amount: '100', duration: 3600 });
 * ```
 */

import { LucidSDK } from "./sdk/sdk.js";
import type { SDKOptions } from "./lib/config.js";

export interface LucidSDKOptions {
  /** Lucid API key (lk_live_... or lk_test_...). Falls back to LUCID_BEARER_AUTH env var. */
  apiKey?: string;
  /** Default chain for v2 endpoints. Can be overridden per call. */
  chain?: string;
  /** Override the server URL. */
  serverURL?: string;
  /** Timeout in milliseconds. */
  timeoutMs?: number;
}

/**
 * Create a LucidSDK instance with typed options.
 *
 * @deprecated Use `@lucid-l2/sdk` instead. This Speakeasy-generated HTTP SDK
 * is deprecated in favour of the embeddable SDK at `offchain/packages/sdk/`.
 * See https://github.com/raijinlabs/Lucid-L2 for migration details.
 */
export function createLucidSDK(options: LucidSDKOptions = {}): LucidSDK {
  const sdkOptions: Record<string, unknown> = {};

  if (options.serverURL) sdkOptions["serverURL"] = options.serverURL;
  if (options.timeoutMs) sdkOptions["timeoutMs"] = options.timeoutMs;
  if (options.chain) sdkOptions["chain"] = options.chain;
  if (options.apiKey) sdkOptions["bearerAuth"] = options.apiKey;

  return new LucidSDK(sdkOptions as SDKOptions);
}

export { LucidSDK };
