/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type Anchor = {
  chain?: string | undefined;
  tx?: string | undefined;
  root?: string | undefined;
  epochId?: string | undefined;
};

export type Receipt = {
  runId: string;
  modelPassportId: string;
  computePassportId: string;
  policyHash: string;
  runtime: string;
  tokensIn: number;
  tokensOut: number;
  ttftMs: number;
  totalLatencyMs?: number | undefined;
  timestamp: number;
  receiptHash: string;
  signature: string;
  merkleLeafIndex?: number | undefined;
  anchor?: Anchor | undefined;
};

/** @internal */
export const Anchor$inboundSchema: z.ZodMiniType<Anchor, unknown> = z.pipe(
  z.object({
    chain: types.optional(types.string()),
    tx: types.optional(types.string()),
    root: types.optional(types.string()),
    epoch_id: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "epoch_id": "epochId",
    });
  }),
);
/** @internal */
export type Anchor$Outbound = {
  chain?: string | undefined;
  tx?: string | undefined;
  root?: string | undefined;
  epoch_id?: string | undefined;
};

/** @internal */
export const Anchor$outboundSchema: z.ZodMiniType<Anchor$Outbound, Anchor> = z
  .pipe(
    z.object({
      chain: z.optional(z.string()),
      tx: z.optional(z.string()),
      root: z.optional(z.string()),
      epochId: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        epochId: "epoch_id",
      });
    }),
  );

export function anchorToJSON(anchor: Anchor): string {
  return JSON.stringify(Anchor$outboundSchema.parse(anchor));
}
export function anchorFromJSON(
  jsonString: string,
): SafeParseResult<Anchor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Anchor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Anchor' from JSON`,
  );
}

/** @internal */
export const Receipt$inboundSchema: z.ZodMiniType<Receipt, unknown> = z.pipe(
  z.object({
    run_id: types.string(),
    model_passport_id: types.string(),
    compute_passport_id: types.string(),
    policy_hash: types.string(),
    runtime: types.string(),
    tokens_in: types.number(),
    tokens_out: types.number(),
    ttft_ms: types.number(),
    total_latency_ms: types.optional(types.number()),
    timestamp: types.number(),
    receipt_hash: types.string(),
    signature: types.string(),
    merkle_leaf_index: types.optional(types.number()),
    anchor: types.optional(z.lazy(() => Anchor$inboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      "run_id": "runId",
      "model_passport_id": "modelPassportId",
      "compute_passport_id": "computePassportId",
      "policy_hash": "policyHash",
      "tokens_in": "tokensIn",
      "tokens_out": "tokensOut",
      "ttft_ms": "ttftMs",
      "total_latency_ms": "totalLatencyMs",
      "receipt_hash": "receiptHash",
      "merkle_leaf_index": "merkleLeafIndex",
    });
  }),
);
/** @internal */
export type Receipt$Outbound = {
  run_id: string;
  model_passport_id: string;
  compute_passport_id: string;
  policy_hash: string;
  runtime: string;
  tokens_in: number;
  tokens_out: number;
  ttft_ms: number;
  total_latency_ms?: number | undefined;
  timestamp: number;
  receipt_hash: string;
  signature: string;
  merkle_leaf_index?: number | undefined;
  anchor?: Anchor$Outbound | undefined;
};

/** @internal */
export const Receipt$outboundSchema: z.ZodMiniType<Receipt$Outbound, Receipt> =
  z.pipe(
    z.object({
      runId: z.string(),
      modelPassportId: z.string(),
      computePassportId: z.string(),
      policyHash: z.string(),
      runtime: z.string(),
      tokensIn: z.int(),
      tokensOut: z.int(),
      ttftMs: z.int(),
      totalLatencyMs: z.optional(z.int()),
      timestamp: z.int(),
      receiptHash: z.string(),
      signature: z.string(),
      merkleLeafIndex: z.optional(z.int()),
      anchor: z.optional(z.lazy(() => Anchor$outboundSchema)),
    }),
    z.transform((v) => {
      return remap$(v, {
        runId: "run_id",
        modelPassportId: "model_passport_id",
        computePassportId: "compute_passport_id",
        policyHash: "policy_hash",
        tokensIn: "tokens_in",
        tokensOut: "tokens_out",
        ttftMs: "ttft_ms",
        totalLatencyMs: "total_latency_ms",
        receiptHash: "receipt_hash",
        merkleLeafIndex: "merkle_leaf_index",
      });
    }),
  );

export function receiptToJSON(receipt: Receipt): string {
  return JSON.stringify(Receipt$outboundSchema.parse(receipt));
}
export function receiptFromJSON(
  jsonString: string,
): SafeParseResult<Receipt, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Receipt$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Receipt' from JSON`,
  );
}
