// PROXY — real implementation moved to @lucid-l2/engine
export {
  CONFIG_VERSION,
  ConfigurationManager,
  configManager,
  IGAS_PER_CALL,
  MGAS_PER_ROOT,
  IGAS_PER_BATCH,
  LUCID_DECIMALS,
  COMPUTE_UNITS,
  API_PORT,
  MAX_BATCH_SIZE,
  getCurrentConfig,
  getLUCID_MINT,
  getRPC_URL,
  getPROGRAM_ID,
  getCOMMITMENT,
  LUCID_MINT,
  RPC_URL,
  PROGRAM_ID,
  COMMITMENT,
  LLM_CONFIG,
  USE_INTERNAL_LLM,
  N8N_CONFIG,
  N8N_ENABLED,
  N8N_URL,
  N8N_HMAC_SECRET,
  N8N_API_KEY,
  MEMORY_WALLET_PATH,
} from '../../packages/engine/src/config/config';
export type { Environment, EnvironmentConfig } from '../../packages/engine/src/config/config';
