/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @lucid/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx passportsCreate.example.ts
 */

import { LucidSDK } from "@lucid/sdk";

const lucidSDK = new LucidSDK();

async function main() {
  const result = await lucidSDK.passports.create({
    type: "dataset",
    owner: "<value>",
    metadata: {
      "key": "<value>",
      "key1": "<value>",
      "key2": "<value>",
    },
  });

  console.log(result);
}

main().catch(console.error);
