/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Policy = {
  version: string;
  constraints?: { [k: string]: any } | undefined;
  preferences?: { [k: string]: any } | undefined;
  fallback?: { [k: string]: any } | undefined;
};

export const Policy$zodSchema: z.ZodType<Policy> = z.object({
  constraints: z.record(z.string(), z.any()).optional(),
  fallback: z.record(z.string(), z.any()).optional(),
  preferences: z.record(z.string(), z.any()).optional(),
  version: z.string(),
});
