/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Anchor = {
  chain?: string | undefined;
  tx?: string | undefined;
  root?: string | undefined;
  epoch_id?: string | undefined;
};

export const Anchor$zodSchema: z.ZodType<Anchor> = z.object({
  chain: z.string().optional(),
  epoch_id: z.string().optional(),
  root: z.string().optional(),
  tx: z.string().optional(),
});

export type Receipt = {
  run_id: string;
  model_passport_id: string;
  compute_passport_id: string;
  policy_hash: string;
  runtime: string;
  tokens_in: number;
  tokens_out: number;
  ttft_ms: number;
  total_latency_ms?: number | undefined;
  timestamp: number;
  receipt_hash: string;
  signature: string;
  merkle_leaf_index?: number | undefined;
  anchor?: Anchor | undefined;
};

export const Receipt$zodSchema: z.ZodType<Receipt> = z.object({
  anchor: z.lazy(() => Anchor$zodSchema).optional(),
  compute_passport_id: z.string(),
  merkle_leaf_index: z.int().optional(),
  model_passport_id: z.string(),
  policy_hash: z.string(),
  receipt_hash: z.string(),
  run_id: z.string(),
  runtime: z.string(),
  signature: z.string(),
  timestamp: z.int(),
  tokens_in: z.int(),
  tokens_out: z.int(),
  total_latency_ms: z.int().optional(),
  ttft_ms: z.int(),
});
